---
fixtures:
  symlinks:
    profile: "#{File.dirname(source_dir)}/gitea"
  forge_modules:
    archive: 'puppet/archive'
    inifile: 'puppetlabs/inifile'
    stdlib: 'puppetlabs/stdlib'
    systemd: 'puppet/systemd'
...
